### ISSUE TITLE
anilist import not working??

### ISSUE THREAD

**Issue by Ojojostar** [4Lajf/amq-scripts#10]
i put in my information and clicked authenticate but nothing happened? none of the songs went into anilist. 

![Screenshot 2024-12-19 174819](https://github.com/user-attachments/assets/1600a656-d36c-4184-b60e-27891e293b8b)

**Comment by 4Lajf** [comment]
yeah, it's an old script and might not work, you should really be using the CSL or Training Mode script since it has the features you're probably looking for - making a list with songs from your session. That script was just a workaround because of some missing CSL feature, but it has it now.
Use Kempanator's Custom Song List Game or 4Lajf's Training Mode

https://github.com/xSardine/AMQ-Script-Links/tree/main/gamemode
